In [1]:
!pip install tensorflow

  Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
     ---------------------------------------- 0.0/46.2 kB ? eta -:--:--
     ---------------------------------------- 46.2/46.2 kB 1.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/377.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/377.0 MB 2.3 MB/s eta 0:02:43
   ---------------------------------------- 0.2/377.0 MB 2.0 MB/s eta 0:03:12
   ---------------------------------------- 0.3/377.0 MB 2.4 MB/s eta 0:02:39
   ---------------------------------------- 0.4/377.0 MB 2.3 MB/s eta 0:02:42
   ---------------------------------------- 0.6/377.0 MB 2.6 MB/s eta 0:02:26
   ---------------------------------------- 0.7/377.0 MB 2.8 MB/s eta 0:02:16
   ---------------------------------------- 1.0/377.0 MB 3.0 MB/s eta 0:02:05
   ---------------------------------------- 1.1/377.0 MB 3.1 MB/s eta 0:02:03
   ---------------------------------------- 1.4/377.0 MB 3.3 MB/s eta 0:01:53
   ---------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [2]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [3]:
# Load SketchRNN data from .npz files
def load_data(npz_file):
    data = np.load(npz_file, allow_pickle=True, encoding='latin1')
    num_row = int(len(data['train']) * 0.01)
    return data['train'][:num_row]

In [4]:
# Load datasets
mountain_data = load_data('Quickdraw/sketchrnn/mountain.full.npz')
house_data = load_data('Quickdraw/sketchrnn/house.full.npz')
cake_data = load_data('Quickdraw/sketchrnn/cake.full.npz')
strawberry_data = load_data('Quickdraw/sketchrnn/strawberry.full.npz')
candle_data = load_data('Quickdraw/sketchrnn/candle.full.npz')
necklace_data = load_data('Quickdraw/sketchrnn/necklace.full.npz')
rain_data = load_data('Quickdraw/sketchrnn/rain.full.npz')
umbrella_data = load_data('Quickdraw/sketchrnn/umbrella.full.npz')
vase_data = load_data('Quickdraw/sketchrnn/vase.full.npz')
hat_data = load_data('Quickdraw/sketchrnn/hat.full.npz')
lollipop_data = load_data('Quickdraw/sketchrnn/lollipop.full.npz')
eye_data = load_data('Quickdraw/sketchrnn/eye.full.npz')
fish_data = load_data('Quickdraw/sketchrnn/fish.full.npz')
flower_data = load_data('Quickdraw/sketchrnn/flower.full.npz')      

In [6]:
# Combine datasets
combined_data = np.concatenate([mountain_data, house_data, cake_data, strawberry_data, candle_data, 
necklace_data, rain_data, umbrella_data, vase_data, hat_data, lollipop_data, eye_data, fish_data, flower_data])

In [7]:
print(combined_data.shape)
print(combined_data[9].shape)

(16685,)
(25, 3)


In [8]:
# Define maximum sequence length
max_seq_len = max(len(sketch) for sketch in combined_data)

In [9]:
max_seq_len

147

In [10]:
# Pad sequences to the same length and extract features
def preprocess_data(data, max_seq_len):
    sequences = []
    for sketch in data:
        sequence = []
        for i in range(len(sketch)):
            dx, dy, state = sketch[i]
            sequence.append([dx, dy, state])
        sequences.append(sequence)
    padded_sequences = pad_sequences(sequences, maxlen=max_seq_len, padding='post', dtype='float32')
    return padded_sequences

In [11]:
train_sequences = preprocess_data(combined_data, max_seq_len)

In [12]:
print(train_sequences.shape)
print(train_sequences[9].shape)
print(train_sequences[9])

(16685, 147, 3)
(147, 3)
[[ 195.   15.    0.]
 [ 223.    2.    1.]
 [-360.  -25.    0.]
 [  30.  -97.    0.]
 [  23.  -57.    0.]
 [  87. -183.    0.]
 [   7.   -9.    0.]
 [   4.    0.    0.]
 [  13.   28.    0.]
 [  16.   61.    0.]
 [  35.  154.    0.]
 [  17.  101.    0.]
 [   9.   31.    1.]
 [-162. -281.    0.]
 [   8.   37.    0.]
 [   7.    2.    0.]
 [  18.  -23.    0.]
 [   4.    0.    0.]
 [  16.   18.    0.]
 [   5.    1.    0.]
 [  16.   -5.    0.]
 [  21.    6.    0.]
 [  15.   -6.    0.]
 [   8.   -5.    0.]
 [   2.   -5.    1.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]
 [   0.  

## Augment

In [13]:
import tensorflow as tf

def augment_data(sequences):
    # Example of augmenting sequences by adding Gaussian noise
    noise_factor = 0.05
    augmented_sequences = sequences + noise_factor * np.random.randn(*sequences.shape)
    return augmented_sequences

In [14]:
# Apply data augmentation
augmented_sequences = augment_data(train_sequences)

In [15]:
print(augmented_sequences.shape)
print(augmented_sequences[9].shape)
print(augmented_sequences[9])

(16685, 147, 3)
(147, 3)
[[ 1.95017403e+02  1.49231199e+01  2.08787384e-02]
 [ 2.22975271e+02  1.98092520e+00  9.40708333e-01]
 [-3.60053529e+02 -2.49189928e+01  2.58984794e-04]
 [ 2.99371459e+01 -9.69516779e+01 -6.88861497e-02]
 [ 2.30097040e+01 -5.70452343e+01  2.52831787e-02]
 [ 8.70279071e+01 -1.82946560e+02  4.19857110e-02]
 [ 6.97297224e+00 -9.03532391e+00  2.80048541e-02]
 [ 4.00696712e+00  5.61490205e-02  6.60640489e-02]
 [ 1.30114165e+01  2.80494745e+01  7.15315490e-02]
 [ 1.59731815e+01  6.09270322e+01  7.08753679e-02]
 [ 3.50435063e+01  1.53964075e+02  8.39801794e-02]
 [ 1.70216703e+01  1.00992505e+02  6.62146003e-02]
 [ 9.05020116e+00  3.09708513e+01  1.02106512e+00]
 [-1.62047344e+02 -2.81048380e+02  4.64767766e-02]
 [ 8.06618611e+00  3.70414691e+01  8.26522970e-03]
 [ 6.98185648e+00  1.92482763e+00 -2.05533934e-03]
 [ 1.79533727e+01 -2.29060530e+01 -4.50046109e-02]
 [ 4.01491097e+00  5.82973668e-02  2.75669900e-03]
 [ 1.59080678e+01  1.80147674e+01  2.18931936e-02]
 [ 5.0

## Modelling

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, LSTM, Dense, TimeDistributed

In [17]:
# Define the model architecture
model = Sequential([
    TimeDistributed(Conv1D(filters=64, kernel_size=3, activation='relu'), input_shape=(max_seq_len, 3, 1)),
    TimeDistributed(MaxPooling1D(pool_size=1)),
    TimeDistributed(Flatten()),
    LSTM(256, return_sequences=True),
    LSTM(256),
    Dense(14, activation='softmax')  
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

C:\Users\asus Pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\wrapper.py:27: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ time_distributed                │ (None, 147, 1, 64)     │           256 │
│ (TimeDistributed)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed_1              │ (None, 147, 1, 64)     │             0 │
│ (TimeDistributed)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed_2              │ (None, 147, 64)        │             0 │
│ (TimeDistributed)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 147, 256)       │       328,704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 256)            │       525,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 14)             │         3,598 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 857,870 (3.27 MB)

 Trainable params: 857,870 (3.27 MB)

 Non-trainable params: 0 (0.00 B)

## Train

In [18]:
# Reshape data to add a channel dimension for CNN
train_sequences = np.expand_dims(train_sequences, axis=-1)
augmented_sequences = np.expand_dims(augmented_sequences, axis=-1)

In [19]:
# Assuming you have labels for the combined data
combined_labels = np.concatenate([np.zeros(len(mountain_data)), np.ones(len(house_data)), np.full(len(cake_data), 2),
np.full(len(strawberry_data), 3), np.full(len(candle_data), 4), np.full(len(necklace_data), 5), np.full(len(rain_data), 6),
np.full(len(umbrella_data), 7), np.full(len(vase_data), 8), np.full(len(hat_data), 2), np.full(len(lollipop_data), 9), 
np.full(len(eye_data), 10), np.full(len(fish_data), 11), np.full(len(flower_data), 12)])

In [20]:
# Train the model
model.fit(augmented_sequences, combined_labels, epochs=10, batch_size=64, validation_split=0.2)

Epoch 1/10
209/209 ━━━━━━━━━━━━━━━━━━━━ 299s 1s/step - accuracy: 0.2211 - loss: 2.3128 - val_accuracy: 0.0000e+00 - val_loss: 7.5281
Epoch 2/10
209/209 ━━━━━━━━━━━━━━━━━━━━ 254s 1s/step - accuracy: 0.3549 - loss: 1.8478 - val_accuracy: 0.0000e+00 - val_loss: 6.9925
Epoch 3/10
209/209 ━━━━━━━━━━━━━━━━━━━━ 222s 1s/step - accuracy: 0.4385 - loss: 1.5852 - val_accuracy: 0.0000e+00 - val_loss: 7.8474
Epoch 4/10
209/209 ━━━━━━━━━━━━━━━━━━━━ 217s 1s/step - accuracy: 0.5801 - loss: 1.2573 - val_accuracy: 0.0042 - val_loss: 7.9588
Epoch 5/10
209/209 ━━━━━━━━━━━━━━━━━━━━ 217s 1s/step - accuracy: 0.6843 - loss: 0.9934 - val_accuracy: 0.0021 - val_loss: 8.1630
Epoch 6/10
209/209 ━━━━━━━━━━━━━━━━━━━━ 214s 1s/step - accuracy: 0.7343 - loss: 0.8280 - val_accuracy: 0.0285 - val_loss: 7.8511
Epoch 7/10
209/209 ━━━━━━━━━━━━━━━━━━━━ 219s 1s/step - accuracy: 0.8019 - loss: 0.6526 - val_accuracy: 0.0584 - val_loss: 8.2740
Epoch 8/10
209/209 ━━━━━━━━━━━━━━━━━━━━ 211s 1s/step - accuracy: 0.8106 - loss: 0.597

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.image import load_img, img_to_array

path_to_image = "/Quickdraw/contoh/house.png"

img = load_img(path_to_image, target_size=(150, 150))

x = img_to_array(img)
x /= 255
x = np.expand_dims(x, axis=0)
images = np.vstack([x])
classes = model.predict(images, batch_size=10)
print(classes[0])